[book]
authors = ["kzg.eth"]
language = "en"
multilingual = false
src = "src"
title = "Wallet Privacy Roadmap"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 0
